version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./social_media_platform:/app/social_media_platform
    command: python manage.py runserver 0.0.0.0:8000
